/* ═══════════════════════════════════════════════════════════════════════════
   Icons — Seti UI font (MIT), extension map generated by build-seti-map.py.
   ═══════════════════════════════════════════════════════════════════════════ */
import { path, root } from "./state.js";

/* Seti has glyphs for these but mapping.less never binds them to an extension. */
const SUPP = {
  nix: ["e019", "#519aba"],
  db: ["e022", "#dd4b78"],
  sqlite: ["e022", "#dd4b78"],
  lock: ["e05d", "#7fae42"],
  desktop: ["e019", "#6d8086"],
};
export const FOLDER_PATH =
  '<path d="M1.4 3.2h4.1l1.3 1.7h7.8c.6 0 1 .4 1 1v7c0 .6-.4 1-1 1H1.4c-.6 0-1-.4-1-1V4.2c0-.6.4-1 1-1z"/>';
const FOLDER_SVG = `<svg viewBox="0 0 16 16">${FOLDER_PATH}</svg>`;

export function iconHTML(node) {
  /* An adapter may name its own glyph — a virtual filesystem's tables and rows
     are not files and have no extension to look up. */
  if (node.icon) return `<span class="ico glyph">${esc(node.icon)}</span>`;
  if (node.dir) return `<span class="ico dir">${FOLDER_SVG}</span>`;
  const lower = node.name.toLowerCase(), ext = lower.split(".").pop();
  const e = SETI.name[lower] || SETI.ext[ext] || SUPP[ext] || SETI.default;
  const color = (root.dataset.theme === "light" && SETI.light[ext]) || e[1];
  return `<span class="ico seti" style="color:${color}">&#x${e[0]};</span>`;
}

export const esc = (s) =>
  s.replace(
    /[&<>"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]),
  );
